version: '3'

services:
    petwork-api:
        image: petwork-api:latest
        build: .
        container_name: petwork-srv
        environment: 
            - MONGO_DB_URL=${MONGO_DB_URL}
            - SENDIN_BLUE_API_KEY=${SENDIN_BLUE_API_KEY}
        ports:
            - 80:80